/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package dictionary;

import javax.swing.JButton;

/**
 *
 * @author TienLuong
 */

public class AddWordApp extends javax.swing.JFrame {

    /**
     * Creates new form AddWordApp
     * 
     */
    public AddWordApp(){
        initComponents();
        this.setLocationRelativeTo(null);
    }
    
    public JButton getButton(){
        return okButton;
    }
    
    public String getTu(){
        return inTu.getText();
    }
    
    public String getNghia(){
        return inNghia.getText();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nhaptuButton = new javax.swing.JLabel();
        inTu = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        inNghia = new javax.swing.JTextArea();
        okButton = new javax.swing.JButton();
        ExitButton = new javax.swing.JButton();
        backgound = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Add New Word to Dictionary");
        setMaximumSize(new java.awt.Dimension(810, 530));
        setMinimumSize(new java.awt.Dimension(810, 530));
        getContentPane().setLayout(null);

        nhaptuButton.setBackground(new java.awt.Color(0, 204, 204));
        nhaptuButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        nhaptuButton.setText("Nhập từ");
        nhaptuButton.setOpaque(true);
        getContentPane().add(nhaptuButton);
        nhaptuButton.setBounds(130, 30, 100, 30);

        inTu.setBackground(new java.awt.Color(204, 204, 204));
        inTu.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        inTu.setForeground(new java.awt.Color(153, 0, 0));
        getContentPane().add(inTu);
        inTu.setBounds(260, 30, 440, 30);

        jLabel1.setBackground(new java.awt.Color(0, 204, 204));
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Nhập Nghĩa");
        jLabel1.setOpaque(true);
        getContentPane().add(jLabel1);
        jLabel1.setBounds(130, 70, 100, 30);

        inNghia.setBackground(new java.awt.Color(204, 204, 204));
        inNghia.setColumns(20);
        inNghia.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        inNghia.setForeground(new java.awt.Color(153, 0, 0));
        inNghia.setRows(5);
        inNghia.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(255, 255, 0), new java.awt.Color(255, 153, 0), new java.awt.Color(0, 204, 51), new java.awt.Color(51, 153, 0)));
        jScrollPane1.setViewportView(inNghia);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(90, 110, 610, 270);

        okButton.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        okButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/okbuttons.png"))); // NOI18N
        okButton.setText("OK");
        okButton.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 0, 51)));
        okButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okButtonActionPerformed(evt);
            }
        });
        getContentPane().add(okButton);
        okButton.setBounds(470, 410, 110, 50);

        ExitButton.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        ExitButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/exit-icon.jpg"))); // NOI18N
        ExitButton.setText("EXIT");
        ExitButton.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(102, 0, 0)));
        ExitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitButtonActionPerformed(evt);
            }
        });
        getContentPane().add(ExitButton);
        ExitButton.setBounds(590, 410, 110, 50);

        backgound.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/bk1.jpg"))); // NOI18N
        backgound.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 0, 0)), "Thêm từ vào từ điển", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 3, 18), new java.awt.Color(0, 0, 204))); // NOI18N
        getContentPane().add(backgound);
        backgound.setBounds(0, 0, 800, 500);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    private void ExitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitButtonActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_ExitButtonActionPerformed
    
    private void okButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okButtonActionPerformed
        // xử lý bên Application
    }//GEN-LAST:event_okButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddWordApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddWordApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddWordApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddWordApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
        
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ExitButton;
    private javax.swing.JLabel backgound;
    public javax.swing.JTextArea inNghia;
    public javax.swing.JTextField inTu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel nhaptuButton;
    public javax.swing.JButton okButton;
    // End of variables declaration//GEN-END:variables
}
